title: 김창기 (ChangKi Kim)
description: Machine Learning & DeepLearning Engineer
site_title: "김창기의 개발 일지"

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: keyAI-ops
blog_url: https://keyai-ops.github.io/
email: ckyou1207@gmail.com

# absolute or relative
profile_picture: assets/images/pp.jpg
